### PR TITLE
Update README

### PR DESCRIPTION
**Pull request by pktiuk**
It is part of issue https://github.com/juliagoda/antimicroX/issues/130

### CODE REVIEW

**Comment by juliagoda** [comment]
I don't like the fact that you decide these things yourself. The license has always been mentioned here and I don't know why such trivialities bother you at all. Can't you consult with me first? Same with Windows. You didn't ask if it's worth doing it now or not, you just put a thread on it right away and now you need help, even though it's after that your job to become a collaborator, but others don't know about it, right?

**Comment by sirlucjan** [comment]
I don't want to be picky, but deletion of the license info from README.md is already very much out of the question. It is better to focus on real problems instead of looking for errors where they do not exist.

**Comment by pktiuk** [comment]
License is still very visible on main page of repository, next to list of contributors.
image

Adding it there just makes README less readable, but if you want I can revert this change.

**Comment by juliagoda** [comment]
No it doesn't make it, revert it please. No one else has seen such a problem in years

**Comment by sirlucjan** [comment]
I would suggest that you close this pull request and resend it, with amendments that actually make sense. As for the first two commits, they're OK.

**Comment by pktiuk** [comment]
I will leave this decission to @juliagoda 
If you will close this PR I will open next one without this change.

**Pull request merged**
