### PR TITLE
Improve packaging

### PR DESCRIPTION
**Pull request by pktiuk**
Some improvements in packaging according to Debain guidelines and usage of `lintian`.
According to lintian there are still some things requiring fixes:
```
$ lintian ./antimicroX-3.0.0-Linux.deb 
E: antimicrox: changelog-file-missing-in-native-package
E: antimicrox: maintainer-address-missing juliagoda
E: antimicrox: no-copyright-file
E: antimicrox: no-shlibs-control-file usr/lib/x86_64-linux-gnu/libantilib.so.1
E: antimicrox: package-must-activate-ldconfig-trigger usr/lib/x86_64-linux-gnu/libantilib.so.1
E: antimicrox: unstripped-binary-or-object usr/bin/antimicroX
E: antimicrox: unstripped-binary-or-object usr/lib/x86_64-linux-gnu/libantilib.so.1
W: antimicrox: desktop-mime-but-no-exec-code usr/share/applications/com.github.juliagoda.antimicroX.desktop
W: antimicrox: extended-description-line-too-long
W: antimicrox: non-dev-pkg-with-shlib-symlink usr/lib/x86_64-linux-gnu/libantilib.so.1 usr/lib/x86_64-linux-gnu/libantilib.so
W: antimicrox: package-contains-timestamped-gzip usr/share/man/man1/antimicroX.1.gz 2020-07-25T19:42:14
W: antimicrox: package-name-doesnt-match-sonames libantilib1
```

But it is nothing urgent, but it would be necessary if we would want to add AntimicroX to Debian repositories.

### CODE REVIEW

**Comment by sirlucjan** [comment]
Could you explain the reason for adding libc6 as a relationship? This is one of the basic elements of the system. I doubt it makes any sense to add it as a dependency in case. 

While the other commites make some sense, the one with the addition of libc6, in my opinion, does not.

**Comment by pktiuk** [comment]
@sirlucjan 
This is one of the requirements for packages in Debian repositories.
Just check current package with lintian and you will see in-depth description for every one of these warnings and errors.

**Comment by sirlucjan** [comment]
In that case, it seems to make sense. Years of using other Linux distributions change habits - frankly speaking, I have never encountered such a bug. 

```
namcap antimicrox-git-3.0.r61.gffa39301-1-x86_64.pkg.tar.zst
antimicrox-git W: Referenced library 'libantilib.so.1' is an uninstalled dependency
```

**Comment by pktiuk** [comment]
We learn every day. :smile: 
I gonna trust more experienced devs and their docs.
For now, I will try to fix the rest of these problems with the package, it would make (in long run) possible adding AntiMicroX to official Debian/Ubuntu repositories.

**Comment by pktiuk** [comment]
Removed also 

`E: antimicrox: manpage-not-compressed-with-max-compression usr/share/man/man1/antimicroX.1.gz`

**Pull request merged**
