### PR TITLE
Add Fedora RPM package info to README

### PR DESCRIPTION
**Pull request by gombosg**

### CODE REVIEW

**Comment by sirlucjan** [comment]
Great job, thanks for your help with the development. If I could just suggest a small correction - instead of linking to your fork on github, you could link directly to .spec sources or binaries.

**Comment by gombosg** [comment]
The link is to my Github profile for fame. 😂
The package name is `antimicroX` and Fedora users know that the way to install it is `dnf install antimicroX`. Linking to binaries doesn't make sense, pages like `src.fedoraproject.org` is only used by packagers.
Should I include that command instead of the package name?

**Comment by sirlucjan** [comment]
If that's what you're saying, that's probably how it is. Typing a command makes a lot of sense - you can do it, for example, as in this project:

https://github.com/PapirusDevelopmentTeam/materia-kde

**Comment by juliagoda** [comment]
So if you did it for a fame, then you could add additional link. You could have entered one of those links to README that were in the thread about "Fedora submission" and above give the information about the installation by dnf install. Nie potrzeby pisać tak kpiąco, ale ok, zaakceptuje to po prostu i tyle. No need to write so mockingly, but ok, I'll just accept it and that's it.

**Pull request merged**
